"""Targeted wrong (and alternative right) answers for py_test.py, per study.

Each entry: (chapter, part title prefix, code, expected substring in the result, should pass).
"""

TARGETED = {
    'A': [
        ('ch3', '(a)', 'def potential(theta):\n    return 0.735 * np.sin(theta)\n', 'rather than numbers', False),
        ('ch3', '(c)', 'def generalized_force(theta, thetadot, tau):\n    return tau\n\ndef damping_force(theta, thetadot, tau):\n    return P.b * thetadot\n', 'Check the sign', False),
        ('ch3', '(d)', 'def thetaddot(theta, thetadot, tau):\n    return 3 / (P.m * P.ell**2) * (tau - P.b * thetadot)\n', 'only gravity acts', False),
        ('ch3', '(d)', 'def thetaddot(theta, thetadot, tau):\n    while True:\n        pass\n', 'Stopped after', False),
        ('ch3', '(d)', 'def thetaddot(theta, thetadot, tau):\n    return undefined_name\n', 'NameError', False),
        ('ch4', '(c)', 'def tau_fl(theta, thetadot):\n    return P.m * P.g * P.ell / 2 * np.cos(theta) + P.b * thetadot\n\ndef thetaddot_fl(theta, thetadot, tau_tilde):\n    return 3 / (P.m * P.ell**2) * tau_tilde\n', 'Consistent', True),
        ('ch4', '(c)', 'def tau_fl(theta, thetadot):\n    return 0\n\ndef thetaddot_fl(theta, thetadot, tau_tilde):\n    return 3 / (P.m * P.ell**2) * (tau_tilde - P.b * thetadot - P.m * P.g * P.ell / 2 * np.cos(theta))\n', 'not linear', False),
        ('ch5', 'Transfer', 'def transfer_function(s):\n    return 2 * (3 / (P.m * P.ell**2)) / (s**2 + 3 * P.b / (P.m * P.ell**2) * s)\n', 'expected', False),
        ('ch6', 'A, B', 'A = np.array([[0, 1], [0, -3 * P.b / (P.m * P.ell**2)]])\nB = np.array([0, 3 / (P.m * P.ell**2)])\nC = np.array([1, 0])\nD = 0\n', 'Matches', True),
    ],
    'B': [
        ('ch3', '(a)', 'def potential(z, theta):\n    return 1.225 * (np.cos(theta) - 1)\n', 'rather than numbers', False),
        ('ch3', '(c)', 'def tau(z, theta, zdot, thetadot, F):\n    return np.array([F, 0])\n\ndef damping(z, theta, zdot, thetadot, F):\n    return np.array([P.b * zdot, 0])\n', 'Check the sign', False),
        ('ch3', '(d)', 'def accel(z, theta, zdot, thetadot, F):\n    c = np.cos(theta)\n    Mq = np.array([[P.m1 + P.m2, P.m1 * P.ell / 2 * c], [P.m1 * P.ell / 2 * c, P.m1 * P.ell**2 / 3]])\n    rhs = np.array([F - P.b * zdot, 0])\n    return np.linalg.solve(Mq, rhs)\n', 'only gravity acts', False),
        ('ch3', '(e)', 'def f(state, F):\n    return np.zeros(3)\n', 'expected 4', False),
        ('ch4', '(b)', 'def accel_lin(x_t, F_t, theta_e):\n    zt, tht, zdt, thdt = x_t.flatten()\n    Mq = np.array([[P.m1 + P.m2, P.m1 * P.ell / 2], [P.m1 * P.ell / 2, P.m1 * P.ell**2 / 3]])\n    rhs = np.array([-P.b * zdt + F_t, P.m1 * P.g * P.ell / 2 * tht])\n    return np.linalg.solve(Mq, rhs)\n', 'θₑ = π', False),
        ('ch5', '(a)', 'def eq1(s):\n    return np.array([(P.m1 + P.m2) * s**2 + P.b * s, P.m1 * P.ell / 2 * s**2])\n\ndef eq2(s):\n    k = P.m1 * P.ell / 2\n    return np.array([k * s**2, k * (2 * P.ell / 3 * s**2 - P.g)])\n', 'Matches', True),
        ('ch5', '(b)', 'J = P.m1 * P.ell / 6 + P.m2 * 2 * P.ell / 3\ndef den(s, b):\n    return J * s**4 + b * 2 * P.ell / 3 * s**3 - (P.m1 + P.m2) * P.g * s**2 - b * P.g * s\ndef Z_F(s):\n    return (2 * P.ell / 3 * s**2 - P.g) / den(s, P.b)\ndef Th_F(s):\n    return -s**2 / den(s, P.b)\ndef Z_F0(s):\n    return Z_F(s)\ndef Th_F0(s):\n    return Th_F(s)\n', 'without P.b', False),
        ('ch8', '(d) Low', 'q = np.sqrt(3 * P.g / (2 * P.ell))\ndef filt(s, k_DC):\n    return -3 / (2 * P.ell * k_DC) / (s + q)\ndef char_out(s, kP, kD):\n    return 2 * ((1 + kD) * s**2 + (kP - q * kD) * s - q * kP)\ndef z_cl(s, kP, kD):\n    return 2 * kP * (s - q) / char_out(s, kP, kD)\n', 'Matches', True),
        ('p6', 'Closed', 'def L(s, kP, kD):\n    return (-2 * P.ell / 3 * s**2 + P.g) / (s**3 + kP * s**2)\n', 'expected', False),
        ('ch12', '(a) Integrator', 'A1 = np.zeros((5, 5))\nB1 = np.zeros((5, 1))\n', 'expected', False),
    ],
    'C': [
        ('ch3', '(a)', 'def potential(theta, phi):\n    return 0.05 * (phi - theta)**2\n', 'rather than numbers', False),
        ('ch3', '(c)', 'def generalized_force(theta, phi, thetadot, phidot, tau):\n    return np.array([tau, 0.0])\n\ndef damping_force(theta, phi, thetadot, phidot, tau):\n    return np.array([P.b * (thetadot - phidot), P.b * (phidot - thetadot)])\n', 'Check the sign', False),
        ('ch3', '(d)', 'def accelerations(theta, phi, thetadot,\n                  phidot, tau):\n    return ((tau - P.b * (thetadot - phidot)) / P.Js,\n            -P.b * (phidot - thetadot) / P.Jp)\n', 'only the spring acts', False),
        ('ch3', '(d)', 'def accelerations(theta, phi, thetadot,\n                  phidot, tau):\n    return ((tau + P.b * (thetadot - phidot) - P.k * (theta - phi)) / P.Js,\n            (P.b * (phidot - thetadot) - P.k * (phi - theta)) / P.Jp)\n', 'only the damper acts', False),
        ('ch3', '(d)', 'def accelerations(theta, phi, thetadot,\n                  phidot, tau):\n    return ((- P.b * (thetadot - phidot) - P.k * (theta - phi)) / P.Js,\n            (-P.b * (phidot - thetadot) - P.k * (phi - theta)) / P.Jp)\n', 'only the torque acts', False),
        ('ch4', '(a)', 'def phi_e(theta_e):\n    return 0.0\n\ndef tau_e(theta_e):\n    return 0.0\n', 'expected', False),
        ('ch5', '(a)', 'def eq_theta(s):\n    return np.array([P.Js * s**2 + P.b * s + P.k, -(P.b * s + P.k), 1])\n\ndef eq_phi(s):\n    g = P.b * s + P.k\n    return np.array([g, -(P.Jp * s**2 + g), 0])\n', 'Matches', True),
        ('ch5', '(b)', 'def theta_over_tau(s):\n    return 1 / ((P.Js + P.Jp) * s**2)\n\ndef phi_over_tau(s):\n    return 0 * s\n', 'expected', False),
        ('ch6', 'A, B', 'Js, Jp, k, b = P.Js, P.Jp, P.k, P.b\nA = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [-k / Js, k / Js, -b / Js, b / Js], [k / Jp, -k / Jp, b / Jp, -b / Jp]])\nB = np.array([[0], [0], [1 / Js], [0]])\nC = np.array([[1, 0, 0, 0], [-1, 1, 0, 0]])\nD = 0\n', 'has 1 value', False),
        ('ch6', 'A, B', 'Js, Jp, k, b = P.Js, P.Jp, P.k, P.b\nA = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [-k / Js, k / Js, -b / Js, b / Js], [k / Jp, -k / Jp, b / Jp, -b / Jp]])\nB = np.array([[0], [0], [1 / Js], [0]])\nC = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])\nD = np.zeros((2, 1))\n', 'expected', False),
        ('ch8', '(b) Inner loop: closed', 'J = P.Js + P.Jp\ndef inner_char_poly(s, kP, kD):\n    return J * s**2 + kD * s + kP\n\ndef inner_cl(s, kP, kD):\n    return kP / inner_char_poly(s, kP, kD)\n', 'Matches', True),
        ('ch8', '(d) Outer loop: closed', 'def outer_char_poly(s, kP, kD):\n    return P.Jp * s**2 + (P.b + P.b * kP) * s + P.k + P.k * kP\n\ndef outer_cl(s, kP, kD):\n    return (P.b * kP * s + P.k * kP) / outer_char_poly(s, kP, kD)\n', 'expected', False),
        ('p6', '(a)', 'def L(s, kP, kD):\n    a3 = P.Jp + P.b * kD\n    return (P.b * s + P.k) / a3 / (s**3 + (P.b + P.b * kP + P.k * kD) / a3 * s**2 + (P.k + P.k * kP) / a3 * s)\n', 'Matches', True),
        ('p6', '(a)', 'def L(s, kP, kD):\n    return (P.b * s + P.k) / (P.Jp * s**3 + (P.b + P.b * kP) * s**2 + (P.k + P.k * kP) * s)\n', 'expected', False),
        ('ch18', '(a) Inner plant', 'def P_in(s, kD, sigma):\n    Js, b, k = P.Js, P.b, P.k\n    return (sigma * s + 1) / (sigma * Js * s**3 + (sigma * b + Js) * s**2 + (sigma * k + b + kD) * s + k)\n', 'book text', True),
        ('ch18', '(b) Outer plant', 'def P_out(s, kD, sigma):\n    return (sigma * s + 1) / (sigma * P.Jp * s**3 + (sigma * P.b + P.Jp) * s**2 + (sigma * P.k + P.b + kD) * s + P.k)\n', 'expected', False),
    ],
    'D': [
        ('ch2', '(a)', 'def kinetic(z, zdot):\n    return 2.5 * zdot**2\n', 'rather than numbers', False),
        ('ch3', '(a)', 'def potential(z):\n    return 1.5 * z**2 + 7\n', 'rather than numbers', False),
        ('ch3', '(c)', 'def generalized_force(z, zdot, F):\n    return F\n\ndef damping_force(z, zdot, F):\n    return P.b * zdot\n', 'Check the sign', False),
        ('ch3', '(d)', 'def zddot(z, zdot, F):\n    return (F - P.b * zdot) / P.m\n', 'only the spring acts', False),
        ('ch3', '(d)', 'def zddot(z, zdot, F):\n    return (F - P.k * z) / P.m\n', 'only damping acts', False),
        ('ch3', '(d)', 'def zddot(z, zdot, F):\n    return (2 * F - P.b * zdot - P.k * z) / P.m\n', 'only the force acts', False),
        ('ch4', '(a)', 'def F_e(z_e):\n    return P.k\n', 'expected', False),
        ('ch4', '(c)', 'def F_fl(z, zdot):\n    return 0\n\ndef zddot_fl(z, zdot, F_tilde):\n    return (F_tilde - P.b * zdot - P.k * z) / P.m\n', 'Consistent', True),
        ('ch4', '(c)', 'def F_fl(z, zdot):\n    return P.k * z\n\ndef zddot_fl(z, zdot, F_tilde):\n    return F_tilde / P.m\n', 'but zddot_fl gives', False),
        ('ch5', '(a)', 'def F_of(s, Z):\n    return P.m * s**2 + P.b * s + P.k\n', 'expected', False),
        ('ch5', '(b)', 'def transfer_function(s):\n    return 1 / (P.m * s**2 + P.b * s + P.k)\n', 'Matches', True),
        ('ch5', '(b)', 'def transfer_function(s):\n    return 1 / (s**2 + P.b * s + P.k)\n', 'expected', False),
        ('ch6', 'Linear', 'A = np.array([[0, 1], [-P.k / P.m, -P.b / P.m]])\nB = np.array([0, 1 / P.m])\nC = np.array([1, 0])\nD = 0\n', 'Matches', True),
        ('ch6', 'Linear', 'A = np.array([[0, 1], [-P.k, -P.b]]) / P.m\nB = np.array([[0], [1 / P.m]])\nC = np.array([[1, 0]])\nD = 0\n', 'expected', False),
        ('ch7', '(b)', 'def char_poly(s, kP, kD):\n    return P.m * s**2 + (P.b + kD) * s + P.k + kP\n\ndef closed_loop(s, kP, kD):\n    return kP / char_poly(s, kP, kD)\n', 'Matches', True),
        ('ch7', '(b)', 'def char_poly(s, kP, kD):\n    return P.m * s**2 + (P.b + kD) * s + kP\n\ndef closed_loop(s, kP, kD):\n    return kP / char_poly(s, kP, kD)\n', 'expected', False),
        ('p6', 'Characteristic', 'def L(s, kP, kD):\n    return (1 / P.m) / (s**2 + (P.b + kD) / P.m * s + (P.k + kP) / P.m)\n', 'expected', False),
    ],
    'E': [
        ('ch3', '(a)', 'def potential(z, theta):\n    return (3.43 * z + 4.9) * np.sin(theta)\n', 'rather than numbers', False),
        ('ch3', '(c)', 'def generalized_force(z, theta, zdot, thetadot, F):\n    return np.array([0, -F * P.ell * np.cos(theta)])\n\ndef damping_force(z, theta, zdot, thetadot, F):\n    return np.array([0, 0])\n', 'Check the sign', False),
        ('ch3', '(c)', 'def generalized_force(z, theta, zdot, thetadot, F):\n    return np.array([0, F * P.ell * np.cos(theta)])\n\ndef damping_force(z, theta, zdot, thetadot, F):\n    return np.array([0, -0.1 * thetadot])\n', 'friction or damping', False),
        ('ch3', '(d)', 'def accelerations(z, theta, zdot, thetadot, F):\n    J = P.m2 * P.ell**2 / 3 + P.m1 * z**2\n    return z * thetadot**2, (F * P.ell * np.cos(theta) - 2 * P.m1 * z * zdot * thetadot) / J\n', 'only gravity acts', False),
        ('ch3', '(d)', 'def accelerations(z, theta, zdot, thetadot, F):\n    J = P.m2 * P.ell**2 / 3 + P.m1 * z**2\n    thd = (F * P.ell * np.cos(theta) - 2 * P.m1 * z * zdot * thetadot\n           - (P.m1 * P.g * z + P.m2 * P.g * P.ell / 2) * np.cos(theta)) / J\n    return -P.g * np.sin(theta), thd\n', 'the beam is turning', False),
        ('ch3', '(d)', 'def accelerations(z, theta, zdot, thetadot, F):\n    J = P.m2 * P.ell**2 / 3 + P.m1 * z**2\n    thd = (F * P.ell * np.cos(theta) - (P.m1 * P.g * z + P.m2 * P.g * P.ell / 2) * np.cos(theta)) / J\n    return z * thetadot**2 - P.g * np.sin(theta), thd\n', 'block sliding on a turning beam', False),
        ('ch4', '(a)', 'def x_e(z_e):\n    return np.array([[z_e], [np.pi], [0], [0]])\n\ndef F_e(z_e):\n    return P.m1 * P.g * z_e / P.ell + P.m2 * P.g / 2\n', 'turns the beam around', False),
        ('ch4', '(c)', 'def F_fl(z, theta, zdot, thetadot):\n    return (P.m1 + P.m2) * P.g / 2\n\ndef thetaddot_fl(z, theta, zdot, thetadot, F_tilde):\n    J = P.m2 * P.ell**2 / 3 + P.m1 * z**2\n    F = (P.m1 + P.m2) * P.g / 2 + F_tilde\n    return (F * P.ell * np.cos(theta) - 2 * P.m1 * z * zdot * thetadot - (P.m1 * P.g * z + P.m2 * P.g * P.ell / 2) * np.cos(theta)) / J\n', 'hold the beam still', False),
        ('ch4', '(c)', 'def F_fl(z, theta, zdot, thetadot):\n    return P.m1 * P.g * z / P.ell + P.m2 * P.g / 2 + 2 * P.m1 * z * zdot * thetadot / (P.ell * np.cos(theta))\n\ndef thetaddot_fl(z, theta, zdot, thetadot, F_tilde):\n    J = P.m2 * P.ell**2 / 3 + P.m1 * z**2\n    return P.ell * np.cos(theta) * F_tilde / J\n', 'Consistent', True),
        ('ch5', '(a)', 'def z_equation(s, Z, Theta, F):\n    return Z + P.g * Theta / s**2\n\ndef theta_equation(s, Z, Theta, F):\n    Je = P.m2 * P.ell**2 / 3 + P.m1 * P.ell**2 / 4\n    return Je * s**2 * Theta + P.m1 * P.g * Z - P.ell * F\n', 'multiple', False),
        ('ch5', '(a)', 'def z_equation(s, Z, Theta, F):\n    return -2 * (s**2 * Z + P.g * Theta)\n\ndef theta_equation(s, Z, Theta, F):\n    Je = P.m2 * P.ell**2 / 3 + P.m1 * P.ell**2 / 4\n    return s**2 * Theta + (P.m1 * P.g * Z - P.ell * F) / Je\n', 'Matches', True),
        ('ch5', '(b)', 'def Theta_over_F(s):\n    Je = P.m2 * P.ell**2 / 3 + P.m1 * P.ell**2 / 4\n    return P.ell / Je / s**2\n\ndef Z_over_F(s):\n    return 0\n\ndef Z_over_Theta(s):\n    return -P.g / s**2\n', 'expected', False),
        ('ch6', 'A, B', 'Je = P.m2 * P.ell**2 / 3 + P.m1 * P.ell**2 / 4\nA = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [0, -P.g, 0, 0], [-P.m1 * P.g / Je, 0, 0, 0]])\nB = np.array([[0], [0], [0], [P.ell / Je]])\nC = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])\nD = 0\n', 'D has 1 value', False),
        ('p6', 'Characteristic', 'def L(s, kP, kD):\n    g = P.g\n    return -g / (s**3 - g * kD * s**2 - g * kP * s)\n', 'negated', False),
    ],
    'F': [
        ('ch2', '(a)', 'def kinetic(z, h, theta, zdot, hdot, thetadot):\n    m = P.mc + 0.5\n    J = P.Jc + 0.5 * P.d**2\n    return 0.5 * m * (zdot**2 + hdot**2) + 0.5 * J * thetadot**2\n', 'rather than numbers', False),
        ('ch3', '(a)', 'def potential(z, h, theta):\n    return P.mc * P.g * h\n', 'Compared up to a constant', False),
        ('ch3', '(b) Damping', 'def damping_force(zdot, hdot, thetadot):\n    return [P.mu * zdot, 0, 0]\n', 'Check the sign', False),
        ('ch3', '(c)', 'def generalized_force(z, h, theta, fr, fl):\n    F = fr + fl\n    return [-F * np.sin(theta), F * np.cos(theta), P.d * (fl - fr)]\n', 'sign of the torque', False),
        ('ch3', '(d)', 'def accelerations(z, h, theta, zdot, hdot, thetadot, fr, fl):\n    m = P.mc + 2 * P.mr\n    J = P.Jc + 2 * P.mr * P.d**2\n    F = fr + fl\n    zddot = (-F * np.sin(theta)) / m\n    hddot = (-m * P.g + F * np.cos(theta)) / m\n    thetaddot = P.d * (fr - fl) / J\n    return zddot, hddot, thetaddot\n', 'only gravity and drag act', False),
        ('ch3', '(d)', 'def accelerations(z, h, theta, zdot, hdot, thetadot, fr, fl):\n    m = P.mc + 2 * P.mr\n    J = P.Jc\n    F = fr + fl\n    zddot = (-F * np.sin(theta) - P.mu * zdot) / m\n    hddot = (-m * P.g + F * np.cos(theta)) / m\n    thetaddot = P.d * (fr - fl) / J\n    return zddot, hddot, thetaddot\n', 'a torque acts', False),
        ('ch3', '(d)', 'def accelerations(z, h, theta, zdot, hdot, thetadot, fr, fl):\n    m = P.mc + 2 * P.mr\n    J = P.Jc + 2 * P.mr * P.d**2\n    F = fr + fl\n    zddot = (-F * np.sin(theta) - P.mu * zdot) / m\n    hddot = (m * P.g + F * np.cos(theta)) / m\n    thetaddot = P.d * (fr - fl) / J\n    return zddot, hddot, thetaddot\n', 'only gravity acts', False),
        ('ch4', '(b)', 'M = P.mc + 2 * P.mr\nJ = P.Jc + 2 * P.mr * P.d**2\nA = np.zeros((6, 6))\nA[0, 3] = A[1, 4] = A[2, 5] = 1\nA[3, 2] = -P.g\nA[3, 3] = -P.mu / M\nB = np.zeros((6, 2))\nB[4, 1] = 1 / M\nB[5, 0] = 1 / J\n', 'expected', False),
        ('ch4', '(c)', 'def F_fl(theta, F_tilde):\n    return (P.mc + 2 * P.mr) * P.g + F_tilde\n\ndef hddot_fl(theta, F_tilde):\n    return F_tilde / (P.mc + 2 * P.mr)\n', 'the VTOL with F = F_fl', False),
        ('ch5', '(c)', 'M = P.mc + 2 * P.mr\nJ = P.Jc + 2 * P.mr * P.d**2\ndef P_theta(s):\n    return (1 / J) / s**2\ndef P_z_theta(s):\n    return P.g / (s**2 + P.mu / M * s)\ndef P_z(s):\n    return P_z_theta(s) * P_theta(s)\n', 'expected', False),
        ('ch6', '(b)', 'M = P.mc + 2 * P.mr\nJ = P.Jc + 2 * P.mr * P.d**2\nA = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [0, -P.g, -P.mu / M, 0], [0, 0, 0, 0]])\nB = np.array([[0], [0], [0], [1 / J]])\nC = np.array([[1, 0, 0, 0], [0, 1, 0, 0]])\nD = 0\n', 'shape 2×1', False),
        ('ch7', '(b)', 'b0 = 1 / (P.mc + 2 * P.mr)\ndef char_poly(s, kP, kD):\n    return 2 * (s**2 + b0 * kD * s + b0 * kP)\ndef closed_loop(s, kP, kD):\n    return 2 * b0 * kP / char_poly(s, kP, kD)\n', 'Matches', True),
        ('p6', '(b) Evans', 'def L_z(s, kP, kD):\n    a = P.mu / (P.mc + 2 * P.mr)\n    b = -P.g\n    return -b / (s**3 + (a + b * kD) * s**2 + b * kP * s)\n', 'expected', False),
    ],
}
